<!DOCTYPE html>
<html>
    <link rel="stylesheet" href="../CSS/MStyle.css">
    <script src="../FUNCTION/Search.js"></script>
    <head>
    </head>
    <body class="body">
    <h1 class="title">Library Catalog System</h1>

    <div class="search-container">
        <input type="text" id="search-bar" name="search" placeholder="Search" autocomplete="off">
        <button id="search-button">Search</button>
    </div>

    </body>
    <footer>

    </footer>
</html>
